import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from "next/font/google";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import { CartProvider } from "./context/cartContext";
import { Toaster } from "react-hot-toast";
import TopHeader from "@/components/header/TopHeader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
  variable: "--font-poppins", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} font-poppins  antialiased `}
      >
        <CartProvider>
          <TopHeader/>
        <Header/>
        {children}
        <Toaster/>
        </CartProvider>
        <Footer/>
      </body>
    </html>
  );
}
